export const continents = {
  Europe: [
    "MD",
    "AX",
    "EE",
    "PT",
    "SI",
    "FR",
    "DK",
    "UA",
    "LI",
    "LT",
    "AT",
    "ME",
    "AD",
    "IT",
    "CH",
    "FO",
    "GR",
    "RU",
    "AL",
    "DE",
    "XK",
    "HR",
    "CZ",
    "SM",
    "FI",
    "LU",
    "JE",
    "GB",
    "GI",
    "SK",
    "IS",
    "MK",
    "SJ",
    "NL",
    "BY",
    "MT",
    "GG",
    "RS",
    "IE",
    "VA",
    "ES",
    "BG",
    "PL",
    "MC",
    "HU",
    "IM",
    "LV",
    "NO",
    "RO",
    "CY",
    "SE",
    "BE",
    "BA",
  ],
  Asia: [
    "MY",
    "TW",
    "TJ",
    "KR",
    "KZ",
    "LB",
    "KW",
    "OM",
    "BN",
    "LA",
    "AE",
    "PK",
    "AM",
    "GE",
    "JP",
    "SA",
    "YE",
    "BH",
    "IR",
    "PS",
    "IN",
    "MM",
    "SY",
    "SG",
    "BT",
    "NP",
    "JO",
    "HK",
    "BD",
    "AF",
    "KG",
    "MV",
    "TL",
    "IQ",
    "PH",
    "QA",
    "ID",
    "KH",
    "MO",
    "TR",
    "UZ",
    "KP",
    "TH",
    "LK",
    "MN",
    "VN",
    "TM",
    "IL",
    "AZ",
    "CN",
  ],
  Africa: [
    "KM",
    "SS",
    "RW",
    "UG",
    "MA",
    "DZ",
    "ET",
    "GA",
    "LS",
    "TD",
    "TG",
    "NE",
    "SH",
    "GH",
    "LR",
    "BW",
    "SD",
    "CD",
    "ZM",
    "BI",
    "CM",
    "TZ",
    "LY",
    "ST",
    "SO",
    "DJ",
    "KE",
    "SL",
    "ER",
    "SZ",
    "GM",
    "IO",
    "EH",
    "SN",
    "MG",
    "GN",
    "GQ",
    "CV",
    "CI",
    "NG",
    "YT",
    "ZA",
    "BJ",
    "TN",
    "MW",
    "MR",
    "SC",
    "CF",
    "ZW",
    "BF",
    "ML",
    "MZ",
    "EG",
    "RE",
    "GW",
    "MU",
    "CG",
    "NA",
    "AO",
  ],
  Americas: [
    "MS",
    "TC",
    "CR",
    "UY",
    "LC",
    "GY",
    "BO",
    "HT",
    "PM",
    "MF",
    "PE",
    "JM",
    "BS",
    "GT",
    "GD",
    "NI",
    "PY",
    "BZ",
    "PA",
    "KN",
    "HN",
    "BQ",
    "VI",
    "AG",
    "GP",
    "SV",
    "US",
    "AI",
    "BL",
    "SR",
    "CW",
    "CL",
    "VG",
    "AW",
    "GF",
    "VE",
    "VC",
    "BB",
    "UM",
    "EC",
    "CA",
    "GL",
    "KY",
    "MQ",
    "SX",
    "BM",
    "BR",
    "CO",
    "CU",
    "DO",
    "DM",
    "PR",
    "TT",
    "AR",
    "MX",
    "FK",
  ],
};

export const currencies = [
  { code: "AFA", name: "Afghan Afghani", locale: "fa-AF" },
  { code: "ALL", name: "Albanian Lek", locale: "sq-AL" },
  { code: "DZD", name: "Algerian Dinar", locale: "ar-DZ" },
  { code: "AOA", name: "Angolan Kwanza", locale: "pt-AO" },
  { code: "ARS", name: "Argentine Peso", locale: "es-AR" },
  { code: "AMD", name: "Armenian Dram", locale: "hy-AM" },
  { code: "AWG", name: "Aruban Florin", locale: "nl-AW" },
  { code: "AUD", name: "Australian Dollar", locale: "en-AU" },
  { code: "AZN", name: "Azerbaijani Manat", locale: "az-AZ" },
  { code: "BSD", name: "Bahamian Dollar", locale: "en-BS" },
  { code: "BHD", name: "Bahraini Dinar", locale: "ar-BH" },
  { code: "BDT", name: "Bangladeshi Taka", locale: "bn-BD" },
  { code: "BBD", name: "Barbadian Dollar", locale: "en-BB" },
  { code: "BYR", name: "Belarusian Ruble", locale: "be-BY" },
  { code: "BEF", name: "Belgian Franc", locale: "fr-BE" },
  { code: "BZD", name: "Belize Dollar", locale: "en-BZ" },
  { code: "BMD", name: "Bermudan Dollar", locale: "en-BM" },
  { code: "BTN", name: "Bhutanese Ngultrum", locale: "dz-BT" },
  { code: "BTC", name: "Bitcoin", locale: "en-US" },
  { code: "BOB", name: "Bolivian Boliviano", locale: "es-BO" },
  { code: "BAM", name: "Bosnia-Herzegovina Convertible Mark", locale: "bs-BA" },
  { code: "BWP", name: "Botswanan Pula", locale: "en-BW" },
  { code: "BRL", name: "Brazilian Real", locale: "pt-BR" },
  { code: "GBP", name: "British Pound Sterling", locale: "en-GB" },
  { code: "BND", name: "Brunei Dollar", locale: "ms-BN" },
  { code: "BGN", name: "Bulgarian Lev", locale: "bg-BG" },
  { code: "BIF", name: "Burundian Franc", locale: "fr-BI" },
  { code: "KHR", name: "Cambodian Riel", locale: "km-KH" },
  { code: "CAD", name: "Canadian Dollar", locale: "en-CA" },
  { code: "CVE", name: "Cape Verdean Escudo", locale: "pt-CV" },
  { code: "KYD", name: "Cayman Islands Dollar", locale: "en-KY" },
  { code: "XOF", name: "CFA Franc BCEAO", locale: "fr-SN" },
  { code: "XAF", name: "CFA Franc BEAC", locale: "fr-CM" },
  { code: "XPF", name: "CFP Franc", locale: "fr-PF" },
  { code: "CLP", name: "Chilean Peso", locale: "es-CL" },
  { code: "CLF", name: "Chilean Unit of Account", locale: "es-CL" },
  { code: "CNY", name: "Chinese Yuan", locale: "zh-CN" },
  { code: "COP", name: "Colombian Peso", locale: "es-CO" },
  { code: "KMF", name: "Comorian Franc", locale: "fr-KM" },
  { code: "CDF", name: "Congolese Franc", locale: "fr-CD" },
  { code: "CRC", name: "Costa Rican Colón", locale: "es-CR" },
  { code: "HRK", name: "Croatian Kuna", locale: "hr-HR" },
  { code: "CUC", name: "Cuban Convertible Peso", locale: "es-CU" },
  { code: "CZK", name: "Czech Republic Koruna", locale: "cs-CZ" },
  { code: "DKK", name: "Danish Krone", locale: "da-DK" },
  { code: "DJF", name: "Djiboutian Franc", locale: "fr-DJ" },
  { code: "DOP", name: "Dominican Peso", locale: "es-DO" },
  { code: "XCD", name: "East Caribbean Dollar", locale: "en-GD" },
  { code: "EGP", name: "Egyptian Pound", locale: "ar-EG" },
  { code: "ERN", name: "Eritrean Nakfa", locale: "ti-ER" },
  { code: "EEK", name: "Estonian Kroon", locale: "et-EE" },
  { code: "ETB", name: "Ethiopian Birr", locale: "am-ET" },
  { code: "EUR", name: "Euro", locale: "de-DE" },
  { code: "FKP", name: "Falkland Islands Pound", locale: "en-FK" },
  { code: "FJD", name: "Fijian Dollar", locale: "en-FJ" },
  { code: "GMD", name: "Gambian Dalasi", locale: "en-GM" },
  { code: "GEL", name: "Georgian Lari", locale: "ka-GE" },
  { code: "DEM", name: "German Mark", locale: "de-DE" },
  { code: "GHS", name: "Ghanaian Cedi", locale: "en-GH" },
  { code: "GIP", name: "Gibraltar Pound", locale: "en-GI" },
  { code: "GRD", name: "Greek Drachma", locale: "el-GR" },
  { code: "GTQ", name: "Guatemalan Quetzal", locale: "es-GT" },
  { code: "GNF", name: "Guinean Franc", locale: "fr-GN" },
  { code: "GYD", name: "Guyanaese Dollar", locale: "en-GY" },
  { code: "HTG", name: "Haitian Gourde", locale: "ht-HT" },
  { code: "HNL", name: "Honduran Lempira", locale: "es-HN" },
  { code: "HKD", name: "Hong Kong Dollar", locale: "zh-HK" },
  { code: "HUF", name: "Hungarian Forint", locale: "hu-HU" },
  { code: "ISK", name: "Icelandic Króna", locale: "is-IS" },
  { code: "INR", name: "Indian Rupee", locale: "hi-IN" },
  { code: "IDR", name: "Indonesian Rupiah", locale: "id-ID" },
  { code: "IRR", name: "Iranian Rial", locale: "fa-IR" },
  { code: "IQD", name: "Iraqi Dinar", locale: "ar-IQ" },
  { code: "ILS", name: "Israeli New Sheqel", locale: "he-IL" },
  { code: "ITL", name: "Italian Lira", locale: "it-IT" },
  { code: "JMD", name: "Jamaican Dollar", locale: "en-JM" },
  { code: "JPY", name: "Japanese Yen", locale: "ja-JP" },
  { code: "JOD", name: "Jordanian Dinar", locale: "ar-JO" },
  { code: "KZT", name: "Kazakhstani Tenge", locale: "kk-KZ" },
  { code: "KES", name: "Kenyan Shilling", locale: "sw-KE" },
  { code: "KWD", name: "Kuwaiti Dinar", locale: "ar-KW" },
  { code: "KGS", name: "Kyrgystani Som", locale: "ky-KG" },
  { code: "LAK", name: "Laotian Kip", locale: "lo-LA" },
  { code: "LVL", name: "Latvian Lats", locale: "lv-LV" },
  { code: "LBP", name: "Lebanese Pound", locale: "ar-LB" },
  { code: "LSL", name: "Lesotho Loti", locale: "st-LS" },
  { code: "LRD", name: "Liberian Dollar", locale: "en-LR" },
  { code: "LYD", name: "Libyan Dinar", locale: "ar-LY" },
  { code: "LTC", name: "Litecoin", locale: "en-US" },
  { code: "LTL", name: "Lithuanian Litas", locale: "lt-LT" },
  { code: "MOP", name: "Macanese Pataca", locale: "zh-MO" },
  { code: "MKD", name: "Macedonian Denar", locale: "mk-MK" },
  { code: "MGA", name: "Malagasy Ariary", locale: "mg-MG" },
  { code: "MWK", name: "Malawian Kwacha", locale: "en-MW" },
  { code: "MYR", name: "Malaysian Ringgit", locale: "ms-MY" },
  { code: "MVR", name: "Maldivian Rufiyaa", locale: "dv-MV" },
  { code: "MRO", name: "Mauritanian Ouguiya", locale: "ar-MR" },
  { code: "MUR", name: "Mauritian Rupee", locale: "en-MU" },
  { code: "MXN", name: "Mexican Peso", locale: "es-MX" },
  { code: "MDL", name: "Moldovan Leu", locale: "ro-MD" },
  { code: "MNT", name: "Mongolian Tugrik", locale: "mn-MN" },
  { code: "MAD", name: "Moroccan Dirham", locale: "ar-MA" },
  { code: "MZM", name: "Mozambican Metical", locale: "pt-MZ" },
  { code: "MMK", name: "Myanmar Kyat", locale: "my-MM" },
  { code: "NAD", name: "Namibian Dollar", locale: "en-NA" },
  { code: "NPR", name: "Nepalese Rupee", locale: "ne-NP" },
  { code: "ANG", name: "Netherlands Antillean Guilder", locale: "nl-CW" },
  { code: "TWD", name: "New Taiwan Dollar", locale: "zh-TW" },
  { code: "NZD", name: "New Zealand Dollar", locale: "en-NZ" },
  { code: "NIO", name: "Nicaraguan Córdoba", locale: "es-NI" },
  { code: "NGN", name: "Nigerian Naira", locale: "en-NG" },
  { code: "KPW", name: "North Korean Won", locale: "ko-KP" },
  { code: "NOK", name: "Norwegian Krone", locale: "no-NO" },
  { code: "OMR", name: "Omani Rial", locale: "ar-OM" },
  { code: "PKR", name: "Pakistani Rupee", locale: "ur-PK" },
  { code: "PAB", name: "Panamanian Balboa", locale: "es-PA" },
  { code: "PGK", name: "Papua New Guinean Kina", locale: "en-PG" },
  { code: "PYG", name: "Paraguayan Guarani", locale: "es-PY" },
  { code: "PEN", name: "Peruvian Nuevo Sol", locale: "es-PE" },
  { code: "PHP", name: "Philippine Peso", locale: "fil-PH" },
  { code: "PLN", name: "Polish Zloty", locale: "pl-PL" },
  { code: "QAR", name: "Qatari Rial", locale: "ar-QA" },
  { code: "RON", name: "Romanian Leu", locale: "ro-RO" },
  { code: "RUB", name: "Russian Ruble", locale: "ru-RU" },
  { code: "RWF", name: "Rwandan Franc", locale: "rw-RW" },
  { code: "SVC", name: "Salvadoran Colón", locale: "es-SV" },
  { code: "WST", name: "Samoan Tala", locale: "sm-WS" },
  { code: "STD", name: "São Tomé and Príncipe Dobra", locale: "pt-ST" },
  { code: "SAR", name: "Saudi Riyal", locale: "ar-SA" },
  { code: "RSD", name: "Serbian Dinar", locale: "sr-RS" },
  { code: "SCR", name: "Seychellois Rupee", locale: "fr-SC" },
  { code: "SLL", name: "Sierra Leonean Leone", locale: "en-SL" },
  { code: "SGD", name: "Singapore Dollar", locale: "en-SG" },
  { code: "SKK", name: "Slovak Koruna", locale: "sk-SK" },
  { code: "SBD", name: "Solomon Islands Dollar", locale: "en-SB" },
  { code: "SOS", name: "Somali Shilling", locale: "so-SO" },
  { code: "ZAR", name: "South African Rand", locale: "en-ZA" },
  { code: "KRW", name: "South Korean Won", locale: "ko-KR" },
  { code: "SSP", name: "South Sudanese Pound", locale: "en-SS" },
  { code: "XDR", name: "Special Drawing Rights", locale: "en-US" },
  { code: "LKR", name: "Sri Lankan Rupee", locale: "si-LK" },
  { code: "SHP", name: "St. Helena Pound", locale: "en-SH" },
  { code: "SDG", name: "Sudanese Pound", locale: "ar-SD" },
  { code: "SRD", name: "Surinamese Dollar", locale: "nl-SR" },
  { code: "SZL", name: "Swazi Lilangeni", locale: "ss-SZ" },
  { code: "SEK", name: "Swedish Krona", locale: "sv-SE" },
  { code: "CHF", name: "Swiss Franc", locale: "de-CH" },
  { code: "SYP", name: "Syrian Pound", locale: "ar-SY" },
  { code: "TJS", name: "Tajikistani Somoni", locale: "tg-TJ" },
  { code: "TZS", name: "Tanzanian Shilling", locale: "sw-TZ" },
  { code: "THB", name: "Thai Baht", locale: "th-TH" },
  { code: "TOP", name: "Tongan Pa'anga", locale: "to-TO" },
  { code: "TTD", name: "Trinidad & Tobago Dollar", locale: "en-TT" },
  { code: "TND", name: "Tunisian Dinar", locale: "ar-TN" },
  { code: "TRY", name: "Turkish Lira", locale: "tr-TR" },
  { code: "TMT", name: "Turkmenistani Manat", locale: "tk-TM" },
  { code: "UGX", name: "Ugandan Shilling", locale: "sw-UG" },
  { code: "UAH", name: "Ukrainian Hryvnia", locale: "uk-UA" },
  { code: "AED", name: "United Arab Emirates Dirham", locale: "ar-AE" },
  { code: "UYU", name: "Uruguayan Peso", locale: "es-UY" },
  { code: "USD", name: "US Dollar", locale: "en-US" },
  { code: "UZS", name: "Uzbekistan Som", locale: "uz-UZ" },
  { code: "VUV", name: "Vanuatu Vatu", locale: "bi-VU" },
  { code: "VEF", name: "Venezuelan Bolívar", locale: "es-VE" },
  { code: "VND", name: "Vietnamese Dong", locale: "vi-VN" },
  { code: "YER", name: "Yemeni Rial", locale: "ar-YE" },
  { code: "ZMK", name: "Zambian Kwacha", locale: "en-ZM" },
  { code: "ZWL", name: "Zimbabwean Dollar", locale: "en-ZW" },
];
